In [50]:
import pandas as pd
import numpy as np
import statistics as stat
import matplotlib.pyplot as plt

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

In [51]:
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

In [52]:
import pickle

In [53]:
dataset = pd.read_csv("Req_Data_1992.csv")
dataset = dataset.iloc[0:12,:]
mylist = []

In [54]:
dataset

,Year,Month,1992,1993,1994,1995,1996,1997,1998,1999,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,UTTARAKHAND,January,71.3,77.1,56.7,98.9,49.7,42.1,9.6,33.0,...,48.7,1.7,55.6,1.8,11.4,30.9,38.8,73.0,45.9,54.5
1,UTTARAKHAND,Febuary,32.5,70.3,84.2,123.6,89.6,14.9,68.4,11.4,...,9.6,138.9,11.7,27.6,62.1,65.2,11.9,188.3,99.9,62.6
2,UTTARAKHAND,March,46.1,162.8,11.0,79.9,67.1,31.2,106.2,1.4,...,71.7,123.1,18.1,18.8,3.8,18.0,28.1,22.0,68.4,127.3
3,UTTARAKHAND,April,2.9,19.8,69.8,41.4,28.4,90.5,73.0,1.2,...,52.2,41.1,93.0,18.4,13.8,30.9,39.2,24.7,37.6,57.3
4,UTTARAKHAND,May,31.5,71.7,75.6,34.6,18.3,56.1,78.5,50.5,...,120.5,78.8,67.3,77.6,47.0,84.2,9.1,18.2,52.9,38.0
5,UTTARAKHAND,June,117.5,144.7,112.1,138.5,181.6,129.8,163.3,158.9,...,104.2,139.9,332.4,41.9,72.7,223.1,46.0,488.9,62.9,186.6
6,UTTARAKHAND,July,254.4,309.4,476.9,358.3,308.1,290.0,242.9,389.0,...,345.6,522.9,313.3,157.5,455.8,433.3,387.1,413.4,462.7,337.0
7,UTTARAKHAND,August,385.1,282.3,428.2,430.7,441.1,273.3,260.0,285.5,...,294.7,502.8,245.8,202.6,335.7,523.7,419.5,359.4,264.2,305.3
8,UTTARAKHAND,September,152.4,447.0,98.0,282.8,185.6,36.4,120.0,217.9,...,79.1,325.6,190.8,206.6,389.7,148.4,220.6,111.3,107.9,52.6
9,UTTARAKHAND,October,9.0,1.5,5.3,5.1,31.4,9.9,75.5,32.0,...,18.8,25.1,23.1,81.3,8.0,3.4,4.7,29.1,40.8,16.8
10,UTTARAKHAND,November,5.4,7.4,1.7,2.1,0.5,10.8,1.2,0.1,...,6.8,7.8,11.9,12.6,4.5,1.2,3.4,3.2,0.0,2.4
11,UTTARAKHAND,December,0.0,0.0,22.3,20.2,0.0,18.5,0.0,4.7,...,27.0,16.7,0.6,0.9,19.5,2.3,15.5,3.8,44.3,7.2

In [55]:
mean_list =[]
for row_name,row in dataset.iterrows():
    i =0
    mylist = []
    for column_name, column in dataset.transpose().iterrows():
        if(i>1):
            #print(column[row_name])
            mylist.append(column[row_name])
        i=i+1
    #print(mylist)
    mean_list.append(stat.mean(mylist))

dataset["Mean"]=mean_list
print(mean_list)

[44.6, 67.25416666666666, 57.50833333333333, 41.50833333333333, 61.262499999999996, 164.40416666666667, 370.52916666666664, 354.3666666666667, 192.175, 22.279166666666665, 4.258333333333334, 10.7125]

///**i=0
for column_name, column in dataset.transpose().iterrows():
    i=i+1
    if i>2:
        #print(column_name)
        mylist = []
        for index, row in dataset.iterrows():
            mylist.append(row[column_name])
        mylist = mylist[:11]
        dataset.at[12,column_name] = stat.mean(mylist)*//

In [56]:
dataset

,Year,Month,1992,1993,1994,1995,1996,1997,1998,1999,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,Mean
0,UTTARAKHAND,January,71.3,77.1,56.7,98.9,49.7,42.1,9.6,33.0,...,1.7,55.6,1.8,11.4,30.9,38.8,73.0,45.9,54.5,44.600000
1,UTTARAKHAND,Febuary,32.5,70.3,84.2,123.6,89.6,14.9,68.4,11.4,...,138.9,11.7,27.6,62.1,65.2,11.9,188.3,99.9,62.6,67.254167
2,UTTARAKHAND,March,46.1,162.8,11.0,79.9,67.1,31.2,106.2,1.4,...,123.1,18.1,18.8,3.8,18.0,28.1,22.0,68.4,127.3,57.508333
3,UTTARAKHAND,April,2.9,19.8,69.8,41.4,28.4,90.5,73.0,1.2,...,41.1,93.0,18.4,13.8,30.9,39.2,24.7,37.6,57.3,41.508333
4,UTTARAKHAND,May,31.5,71.7,75.6,34.6,18.3,56.1,78.5,50.5,...,78.8,67.3,77.6,47.0,84.2,9.1,18.2,52.9,38.0,61.262500
5,UTTARAKHAND,June,117.5,144.7,112.1,138.5,181.6,129.8,163.3,158.9,...,139.9,332.4,41.9,72.7,223.1,46.0,488.9,62.9,186.6,164.404167
6,UTTARAKHAND,July,254.4,309.4,476.9,358.3,308.1,290.0,242.9,389.0,...,522.9,313.3,157.5,455.8,433.3,387.1,413.4,462.7,337.0,370.529167
7,UTTARAKHAND,August,385.1,282.3,428.2,430.7,441.1,273.3,260.0,285.5,...,502.8,245.8,202.6,335.7,523.7,419.5,359.4,264.2,305.3,354.366667
8,UTTARAKHAND,September,152.4,447.0,98.0,282.8,185.6,36.4,120.0,217.9,...,325.6,190.8,206.6,389.7,148.4,220.6,111.3,107.9,52.6,192.175000
9,UTTARAKHAND,October,9.0,1.5,5.3,5.1,31.4,9.9,75.5,32.0,...,25.1,23.1,81.3,8.0,3.4,4.7,29.1,40.8,16.8,22.279167
10,UTTARAKHAND,November,5.4,7.4,1.7,2.1,0.5,10.8,1.2,0.1,...,7.8,11.9,12.6,4.5,1.2,3.4,3.2,0.0,2.4,4.258333
11,UTTARAKHAND,December,0.0,0.0,22.3,20.2,0.0,18.5,0.0,4.7,...,16.7,0.6,0.9,19.5,2.3,15.5,3.8,44.3,7.2,10.712500

In [57]:
for i in range(12):
    if(dataset.at[i,"Mean"]<50):
        dataset.at[i,"Quality Index"]=0
    if(dataset.at[i,"Mean"]>50 and dataset.at[i,"Mean"]):
        dataset.at[i,"Quality Index"]=1
    if(dataset.at[i,"Mean"]>=200):
        dataset.at[i,"Quality Index"]=2

In [58]:
dataset

,Year,Month,1992,1993,1994,1995,1996,1997,1998,1999,...,2008,2009,2010,2011,2012,2013,2014,2015,Mean,Quality Index
0,UTTARAKHAND,January,71.3,77.1,56.7,98.9,49.7,42.1,9.6,33.0,...,55.6,1.8,11.4,30.9,38.8,73.0,45.9,54.5,44.600000,0.0
1,UTTARAKHAND,Febuary,32.5,70.3,84.2,123.6,89.6,14.9,68.4,11.4,...,11.7,27.6,62.1,65.2,11.9,188.3,99.9,62.6,67.254167,1.0
2,UTTARAKHAND,March,46.1,162.8,11.0,79.9,67.1,31.2,106.2,1.4,...,18.1,18.8,3.8,18.0,28.1,22.0,68.4,127.3,57.508333,1.0
3,UTTARAKHAND,April,2.9,19.8,69.8,41.4,28.4,90.5,73.0,1.2,...,93.0,18.4,13.8,30.9,39.2,24.7,37.6,57.3,41.508333,0.0
4,UTTARAKHAND,May,31.5,71.7,75.6,34.6,18.3,56.1,78.5,50.5,...,67.3,77.6,47.0,84.2,9.1,18.2,52.9,38.0,61.262500,1.0
5,UTTARAKHAND,June,117.5,144.7,112.1,138.5,181.6,129.8,163.3,158.9,...,332.4,41.9,72.7,223.1,46.0,488.9,62.9,186.6,164.404167,1.0
6,UTTARAKHAND,July,254.4,309.4,476.9,358.3,308.1,290.0,242.9,389.0,...,313.3,157.5,455.8,433.3,387.1,413.4,462.7,337.0,370.529167,2.0
7,UTTARAKHAND,August,385.1,282.3,428.2,430.7,441.1,273.3,260.0,285.5,...,245.8,202.6,335.7,523.7,419.5,359.4,264.2,305.3,354.366667,2.0
8,UTTARAKHAND,September,152.4,447.0,98.0,282.8,185.6,36.4,120.0,217.9,...,190.8,206.6,389.7,148.4,220.6,111.3,107.9,52.6,192.175000,1.0
9,UTTARAKHAND,October,9.0,1.5,5.3,5.1,31.4,9.9,75.5,32.0,...,23.1,81.3,8.0,3.4,4.7,29.1,40.8,16.8,22.279167,0.0
10,UTTARAKHAND,November,5.4,7.4,1.7,2.1,0.5,10.8,1.2,0.1,...,11.9,12.6,4.5,1.2,3.4,3.2,0.0,2.4,4.258333,0.0
11,UTTARAKHAND,December,0.0,0.0,22.3,20.2,0.0,18.5,0.0,4.7,...,0.6,0.9,19.5,2.3,15.5,3.8,44.3,7.2,10.712500,0.0

In [59]:
dataset.to_csv('Req_Data_1992_modfied.csv')

In [60]:
dataset = dataset.drop('Mean', 1)

for i in range(12):
    if(dataset.at[i,"Quality Index"]==0):
        dataset.at[i,"Category 1"]=1
    else:
        dataset.at[i,"Category 1"]=0
        
    if(dataset.at[i,"Quality Index"]==1):
        dataset.at[i,"Category 2"]=1
    else:
        dataset.at[i,"Category 2"]=0
        
    if(dataset.at[i,"Quality Index"]==2):
        dataset.at[i,"Category 3"]=1
    else:
        dataset.at[i,"Category 3"]=1

In [61]:
dataset

,Year,Month,1992,1993,1994,1995,1996,1997,1998,1999,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,Quality Index
0,UTTARAKHAND,January,71.3,77.1,56.7,98.9,49.7,42.1,9.6,33.0,...,1.7,55.6,1.8,11.4,30.9,38.8,73.0,45.9,54.5,0.0
1,UTTARAKHAND,Febuary,32.5,70.3,84.2,123.6,89.6,14.9,68.4,11.4,...,138.9,11.7,27.6,62.1,65.2,11.9,188.3,99.9,62.6,1.0
2,UTTARAKHAND,March,46.1,162.8,11.0,79.9,67.1,31.2,106.2,1.4,...,123.1,18.1,18.8,3.8,18.0,28.1,22.0,68.4,127.3,1.0
3,UTTARAKHAND,April,2.9,19.8,69.8,41.4,28.4,90.5,73.0,1.2,...,41.1,93.0,18.4,13.8,30.9,39.2,24.7,37.6,57.3,0.0
4,UTTARAKHAND,May,31.5,71.7,75.6,34.6,18.3,56.1,78.5,50.5,...,78.8,67.3,77.6,47.0,84.2,9.1,18.2,52.9,38.0,1.0
5,UTTARAKHAND,June,117.5,144.7,112.1,138.5,181.6,129.8,163.3,158.9,...,139.9,332.4,41.9,72.7,223.1,46.0,488.9,62.9,186.6,1.0
6,UTTARAKHAND,July,254.4,309.4,476.9,358.3,308.1,290.0,242.9,389.0,...,522.9,313.3,157.5,455.8,433.3,387.1,413.4,462.7,337.0,2.0
7,UTTARAKHAND,August,385.1,282.3,428.2,430.7,441.1,273.3,260.0,285.5,...,502.8,245.8,202.6,335.7,523.7,419.5,359.4,264.2,305.3,2.0
8,UTTARAKHAND,September,152.4,447.0,98.0,282.8,185.6,36.4,120.0,217.9,...,325.6,190.8,206.6,389.7,148.4,220.6,111.3,107.9,52.6,1.0
9,UTTARAKHAND,October,9.0,1.5,5.3,5.1,31.4,9.9,75.5,32.0,...,25.1,23.1,81.3,8.0,3.4,4.7,29.1,40.8,16.8,0.0
10,UTTARAKHAND,November,5.4,7.4,1.7,2.1,0.5,10.8,1.2,0.1,...,7.8,11.9,12.6,4.5,1.2,3.4,3.2,0.0,2.4,0.0
11,UTTARAKHAND,December,0.0,0.0,22.3,20.2,0.0,18.5,0.0,4.7,...,16.7,0.6,0.9,19.5,2.3,15.5,3.8,44.3,7.2,0.0

Starting Model

In [62]:
seed = 7
np.random.seed(seed)

In [63]:
X_train = dataset.iloc[:,2:].astype(float)
Y_train = dataset.iloc[:,-1]

In [64]:
X_train

,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,Quality Index
0,71.3,77.1,56.7,98.9,49.7,42.1,9.6,33.0,29.9,22.7,...,1.7,55.6,1.8,11.4,30.9,38.8,73.0,45.9,54.5,0.0
1,32.5,70.3,84.2,123.6,89.6,14.9,68.4,11.4,69.4,27.9,...,138.9,11.7,27.6,62.1,65.2,11.9,188.3,99.9,62.6,1.0
2,46.1,162.8,11.0,79.9,67.1,31.2,106.2,1.4,37.9,83.4,...,123.1,18.1,18.8,3.8,18.0,28.1,22.0,68.4,127.3,1.0
3,2.9,19.8,69.8,41.4,28.4,90.5,73.0,1.2,18.1,48.2,...,41.1,93.0,18.4,13.8,30.9,39.2,24.7,37.6,57.3,0.0
4,31.5,71.7,75.6,34.6,18.3,56.1,78.5,50.5,83.3,109.1,...,78.8,67.3,77.6,47.0,84.2,9.1,18.2,52.9,38.0,1.0
5,117.5,144.7,112.1,138.5,181.6,129.8,163.3,158.9,313.9,297.3,...,139.9,332.4,41.9,72.7,223.1,46.0,488.9,62.9,186.6,1.0
6,254.4,309.4,476.9,358.3,308.1,290.0,242.9,389.0,420.1,493.0,...,522.9,313.3,157.5,455.8,433.3,387.1,413.4,462.7,337.0,2.0
7,385.1,282.3,428.2,430.7,441.1,273.3,260.0,285.5,436.1,371.7,...,502.8,245.8,202.6,335.7,523.7,419.5,359.4,264.2,305.3,2.0
8,152.4,447.0,98.0,282.8,185.6,36.4,120.0,217.9,195.3,68.3,...,325.6,190.8,206.6,389.7,148.4,220.6,111.3,107.9,52.6,1.0
9,9.0,1.5,5.3,5.1,31.4,9.9,75.5,32.0,1.1,6.3,...,25.1,23.1,81.3,8.0,3.4,4.7,29.1,40.8,16.8,0.0
10,5.4,7.4,1.7,2.1,0.5,10.8,1.2,0.1,7.0,1.4,...,7.8,11.9,12.6,4.5,1.2,3.4,3.2,0.0,2.4,0.0
11,0.0,0.0,22.3,20.2,0.0,18.5,0.0,4.7,0.7,15.1,...,16.7,0.6,0.9,19.5,2.3,15.5,3.8,44.3,7.2,0.0

In [65]:
Y_train

0     0.0
1     1.0
2     1.0
3     0.0
4     1.0
5     1.0
6     2.0
7     2.0
8     1.0
9     0.0
10    0.0
11    0.0
Name: Quality Index, dtype: float64

In [66]:
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y_train)
encoded_Y = encoder.transform(Y_train)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)

In [67]:
dummy_y

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.]])

In [68]:
# define baseline model
def baseline_model():
	# create model
	model = Sequential()
	model.add(Dense(8, input_dim=25, activation='relu'))
	model.add(Dense(3, activation='softmax'))
	# Compile model
	model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

In [69]:
estimator = KerasClassifier(build_fn=baseline_model, epochs=200, batch_size=5, verbose=0)

 kfold = KFold(n_splits=10, shuffle=True, random_state=seed)

In [70]:
results = cross_val_score(estimator, X_train, dummy_y, cv=kfold)

In [71]:
print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

Baseline: 40.00% (48.99%)

In [75]:
filename = 'finalized_model.pkl'
pickle.dump(estimator, open(filename, 'wb'))